# Generated by Django 2.2.7 on 2019-12-01 00:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('timeout', models.DurationField(default=datetime.timedelta(0, 1800))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcserver.Chat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcserver.User')),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcserver.Chat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcserver.User')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcserver.Chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcserver.User')),
            ],
        ),
        migrations.CreateModel(
            name='AccessResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcserver.AccessRequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcserver.User')),
            ],
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcserver.Chat'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_receiver', to='tcserver.User'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_sender', to='tcserver.User'),
        ),
    ]
